[package]
name = "warzone_multi"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"

[profile.release]
opt-level = 3